docker: include bench sources
addresses this:

```
    > [build 12/14] RUN --mount=type=bind,dst=/src cargo fetch --locked --manifest-path=/src/Cargo.toml:
0.196 error: failed to parse manifest at `/src/client/Cargo.toml`
0.196
0.196 Caused by:
0.196   can't find `shard_lookup` bench at `benches/shard_lookup.rs` or `benches/shard_lookup/main.rs`. Please specify bench.path if you want to use a non-default path.
------
Dockerfile:105
--------------------
 103 |
 104 |     # ====== Fetch current dependencies =====
 105 | >>> RUN --mount=type=bind,dst=/src cargo fetch --locked --manifest-path=/src/Cargo.toml
 106 |
 107 |     # ====== Prepopulate dependency caches =====
--------------------
ERROR: failed to build: failed to solve: process "/bin/bash -o pipefail -c cargo fetch --locked --manifest-path=/src/Cargo.toml" did not complete successfully: exit code: 101
```