Patch ext/oxia to build with go1.26
github.com/cockroachdb/swiss needs to be updated.  I'm patching locally
rather than pushing a change upstream as I don't want to drop a PR and
run away if a pebble update breaks things:  it's a fundamental
dependency of oxia-db

```bash
14:27:58 [3] > GOPROXY=off go build -mod=vendor -o /tmp/oxia
vendor/github.com/cockroachdb/swiss/map.go:286:7: undefined: hashFn
vendor/github.com/cockroachdb/swiss/map.go:337:14: undefined: getRuntimeHasher
vendor/github.com/cockroachdb/swiss/map.go:338:22: undefined: fastrand64
vendor/github.com/cockroachdb/swiss/map.go:600:23: undefined: fastrand64
vendor/github.com/cockroachdb/swiss/map.go:649:19: undefined: fastrand64
vendor/github.com/cockroachdb/swiss/map.go:670:20: undefined: fastrand64
vendor/github.com/cockroachdb/swiss/options.go:30:14: undefined: hashFn
```